// Autogenerated from Pigeon (v27.3.0), do not edit directly.
// See also: https://pub.dev/packages/pigeon
@file:Suppress("UNCHECKED_CAST", "ArrayInDataClass")

package io.github.marl0nl.hubspot_flutter_chat

import android.util.Log
import io.flutter.plugin.common.BasicMessageChannel
import io.flutter.plugin.common.BinaryMessenger
import io.flutter.plugin.common.EventChannel
import io.flutter.plugin.common.MessageCodec
import io.flutter.plugin.common.StandardMethodCodec
import io.flutter.plugin.common.StandardMessageCodec
import java.io.ByteArrayOutputStream
import java.nio.ByteBuffer
private object MessagesPigeonUtils {

  fun createConnectionError(channelName: String): FlutterError {
    return FlutterError("channel-error",  "Unable to establish connection on channel: '$channelName'.", "")  }

  fun wrapResult(result: Any?): List<Any?> {
    return listOf(result)
  }

  fun wrapError(exception: Throwable): List<Any?> {
    return if (exception is FlutterError) {
      listOf(
        exception.code,
        exception.message,
        exception.details
      )
    } else {
      listOf(
        exception.javaClass.simpleName,
        exception.toString(),
        "Cause: " + exception.cause + ", Stacktrace: " + Log.getStackTraceString(exception)
      )
    }
  }
  fun doubleEquals(a: Double, b: Double): Boolean {
    // Normalize -0.0 to 0.0 and handle NaN equality.
    return (if (a == 0.0) 0.0 else a) == (if (b == 0.0) 0.0 else b) || (a.isNaN() && b.isNaN())
  }

  fun floatEquals(a: Float, b: Float): Boolean {
    // Normalize -0.0 to 0.0 and handle NaN equality.
    return (if (a == 0.0f) 0.0f else a) == (if (b == 0.0f) 0.0f else b) || (a.isNaN() && b.isNaN())
  }

  fun doubleHash(d: Double): Int {
    // Normalize -0.0 to 0.0 and handle NaN to ensure consistent hash codes.
    val normalized = if (d == 0.0) 0.0 else d
    val bits = java.lang.Double.doubleToLongBits(normalized)
    return (bits xor (bits ushr 32)).toInt()
  }

  fun floatHash(f: Float): Int {
    // Normalize -0.0 to 0.0 and handle NaN to ensure consistent hash codes.
    val normalized = if (f == 0.0f) 0.0f else f
    return java.lang.Float.floatToIntBits(normalized)
  }

  fun deepEquals(a: Any?, b: Any?): Boolean {
    if (a === b) {
      return true
    }
    if (a == null || b == null) {
      return false
    }
    if (a is ByteArray && b is ByteArray) {
      return a.contentEquals(b)
    }
    if (a is IntArray && b is IntArray) {
      return a.contentEquals(b)
    }
    if (a is LongArray && b is LongArray) {
      return a.contentEquals(b)
    }
    if (a is DoubleArray && b is DoubleArray) {
      if (a.size != b.size) return false
      for (i in a.indices) {
        if (!doubleEquals(a[i], b[i])) return false
      }
      return true
    }
    if (a is FloatArray && b is FloatArray) {
      if (a.size != b.size) return false
      for (i in a.indices) {
        if (!floatEquals(a[i], b[i])) return false
      }
      return true
    }
    if (a is Array<*> && b is Array<*>) {
      if (a.size != b.size) return false
      for (i in a.indices) {
        if (!deepEquals(a[i], b[i])) return false
      }
      return true
    }
    if (a is List<*> && b is List<*>) {
      if (a.size != b.size) return false
      val iterA = a.iterator()
      val iterB = b.iterator()
      while (iterA.hasNext() && iterB.hasNext()) {
        if (!deepEquals(iterA.next(), iterB.next())) return false
      }
      return true
    }
    if (a is Map<*, *> && b is Map<*, *>) {
      if (a.size != b.size) return false
      for (entry in a) {
        val key = entry.key
        var found = false
        for (bEntry in b) {
          if (deepEquals(key, bEntry.key)) {
            if (deepEquals(entry.value, bEntry.value)) {
              found = true
              break
            } else {
              return false
            }
          }
        }
        if (!found) return false
      }
      return true
    }
    if (a is Double && b is Double) {
      return doubleEquals(a, b)
    }
    if (a is Float && b is Float) {
      return floatEquals(a, b)
    }
    return a == b
  }

  fun deepHash(value: Any?): Int {
    return when (value) {
      null -> 0
      is ByteArray -> value.contentHashCode()
      is IntArray -> value.contentHashCode()
      is LongArray -> value.contentHashCode()
      is DoubleArray -> {
        var result = 1
        for (item in value) {
          result = 31 * result + doubleHash(item)
        }
        result
      }
      is FloatArray -> {
        var result = 1
        for (item in value) {
          result = 31 * result + floatHash(item)
        }
        result
      }
      is Array<*> -> {
        var result = 1
        for (item in value) {
          result = 31 * result + deepHash(item)
        }
        result
      }
      is List<*> -> {
        var result = 1
        for (item in value) {
          result = 31 * result + deepHash(item)
        }
        result
      }
      is Map<*, *> -> {
        var result = 0
        for (entry in value) {
          result += ((deepHash(entry.key) * 31) xor deepHash(entry.value))
        }
        result
      }
      is Double -> doubleHash(value)
      is Float -> floatHash(value)
      else -> value.hashCode()
    }
  }

}

/**
 * Error class for passing custom error details to Flutter via a thrown PlatformException.
 * @property code The error code.
 * @property message The error message.
 * @property details The error details. Must be a datatype supported by the api codec.
 */
class FlutterError (
  val code: String,
  override val message: String? = null,
  val details: Any? = null
) : RuntimeException()

/**
 * Configuration for the HubSpot mobile chat SDK.
 *
 * Generated class from Pigeon that represents data sent in messages.
 */
data class ChatSetupData (
  /** The public HubSpot portal / Hub ID. */
  val portalId: String,
  /** The HubSpot hublet (data-hosting region), e.g. `na1` / `eu1`. */
  val hublet: String? = null,
  /** The default chatflow to open when none is specified. */
  val defaultChatFlow: String? = null,
  /** The HubSpot environment (`PROD` by default). */
  val environment: String? = null,
  /** Whether to enable verbose native SDK logging. */
  val enableLogging: Boolean
)
 {
  companion object {
    fun fromList(pigeonVar_list: List<Any?>): ChatSetupData {
      val portalId = pigeonVar_list[0] as String
      val hublet = pigeonVar_list[1] as String?
      val defaultChatFlow = pigeonVar_list[2] as String?
      val environment = pigeonVar_list[3] as String?
      val enableLogging = pigeonVar_list[4] as Boolean
      return ChatSetupData(portalId, hublet, defaultChatFlow, environment, enableLogging)
    }
  }
  fun toList(): List<Any?> {
    return listOf(
      portalId,
      hublet,
      defaultChatFlow,
      environment,
      enableLogging,
    )
  }
  override fun equals(other: Any?): Boolean {
    if (other == null || other.javaClass != javaClass) {
      return false
    }
    if (this === other) {
      return true
    }
    val other = other as ChatSetupData
    return MessagesPigeonUtils.deepEquals(this.portalId, other.portalId) && MessagesPigeonUtils.deepEquals(this.hublet, other.hublet) && MessagesPigeonUtils.deepEquals(this.defaultChatFlow, other.defaultChatFlow) && MessagesPigeonUtils.deepEquals(this.environment, other.environment) && MessagesPigeonUtils.deepEquals(this.enableLogging, other.enableLogging)
  }

  override fun hashCode(): Int {
    var result = javaClass.hashCode()
    result = 31 * result + MessagesPigeonUtils.deepHash(this.portalId)
    result = 31 * result + MessagesPigeonUtils.deepHash(this.hublet)
    result = 31 * result + MessagesPigeonUtils.deepHash(this.defaultChatFlow)
    result = 31 * result + MessagesPigeonUtils.deepHash(this.environment)
    result = 31 * result + MessagesPigeonUtils.deepHash(this.enableLogging)
    return result
  }
  override fun toString(): String {
    return "ChatSetupData(portalId=$portalId, hublet=$hublet, defaultChatFlow=$defaultChatFlow, environment=$environment, enableLogging=$enableLogging)"
  }
}

/**
 * A visitor identity for authenticated chat.
 *
 * The [identityToken] is minted **server-side** via
 * `POST /visitor-identification/v3/tokens/create`; the client only consumes it.
 *
 * Generated class from Pigeon that represents data sent in messages.
 */
data class VisitorIdentity (
  /** The visitor's email address. */
  val email: String,
  /** The server-minted visitor-identification token. */
  val identityToken: String
)
 {
  companion object {
    fun fromList(pigeonVar_list: List<Any?>): VisitorIdentity {
      val email = pigeonVar_list[0] as String
      val identityToken = pigeonVar_list[1] as String
      return VisitorIdentity(email, identityToken)
    }
  }
  fun toList(): List<Any?> {
    return listOf(
      email,
      identityToken,
    )
  }
  override fun equals(other: Any?): Boolean {
    if (other == null || other.javaClass != javaClass) {
      return false
    }
    if (this === other) {
      return true
    }
    val other = other as VisitorIdentity
    return MessagesPigeonUtils.deepEquals(this.email, other.email) && MessagesPigeonUtils.deepEquals(this.identityToken, other.identityToken)
  }

  override fun hashCode(): Int {
    var result = javaClass.hashCode()
    result = 31 * result + MessagesPigeonUtils.deepHash(this.email)
    result = 31 * result + MessagesPigeonUtils.deepHash(this.identityToken)
    return result
  }
  override fun toString(): String {
    return "VisitorIdentity(email=$email, identityToken=$identityToken)"
  }
}
private open class MessagesPigeonCodec : StandardMessageCodec() {
  override fun readValueOfType(type: Byte, buffer: ByteBuffer): Any? {
    return when (type) {
      129.toByte() -> {
        return (readValue(buffer) as? List<Any?>)?.let {
          ChatSetupData.fromList(it)
        }
      }
      130.toByte() -> {
        return (readValue(buffer) as? List<Any?>)?.let {
          VisitorIdentity.fromList(it)
        }
      }
      else -> super.readValueOfType(type, buffer)
    }
  }
  override fun writeValue(stream: ByteArrayOutputStream, value: Any?)   {
    when (value) {
      is ChatSetupData -> {
        stream.write(129)
        writeValue(stream, value.toList())
      }
      is VisitorIdentity -> {
        stream.write(130)
        writeValue(stream, value.toList())
      }
      else -> super.writeValue(stream, value)
    }
  }
}


/**
 * Dart -> native calls.
 *
 * Generated interface from Pigeon that represents a handler of messages from Flutter.
 */
interface HubspotChatHostApi {
  /**
   * Initialises the native HubSpot chat SDK. Must be called before any other
   * method.
   */
  fun configure(setup: ChatSetupData, callback: (Result<Unit>) -> Unit)
  /** Presents the chat UI, optionally targeting a specific [chatFlow]. */
  fun openChat(chatFlow: String?, callback: (Result<Unit>) -> Unit)
  /** Dismisses the chat UI if it is visible. */
  fun closeChat(callback: (Result<Unit>) -> Unit)
  /** Associates the current session with an identified visitor. */
  fun setUserIdentity(identity: VisitorIdentity, callback: (Result<Unit>) -> Unit)
  /** Sets custom chat properties attached to subsequent conversations. */
  fun setChatProperties(properties: Map<String, String>, callback: (Result<Unit>) -> Unit)
  /**
   * Registers the device push token (FCM on Android, APNs on iOS) so HubSpot
   * can deliver chat push notifications.
   */
  fun setPushToken(token: String, callback: (Result<Unit>) -> Unit)
  /**
   * Asks the native SDK whether it recognises and will handle a push payload.
   * Returns true if the payload was a HubSpot chat notification.
   */
  fun handlePushNotification(data: Map<String, String>, callback: (Result<Boolean>) -> Unit)
  /** Clears the identified visitor and cached conversation state. */
  fun logout(callback: (Result<Unit>) -> Unit)

  companion object {
    /** The codec used by HubspotChatHostApi. */
    val codec: MessageCodec<Any?> by lazy {
      MessagesPigeonCodec()
    }
    /** Sets up an instance of `HubspotChatHostApi` to handle messages through the `binaryMessenger`. */
    @JvmOverloads
    fun setUp(binaryMessenger: BinaryMessenger, api: HubspotChatHostApi?, messageChannelSuffix: String = "") {
      val separatedMessageChannelSuffix = if (messageChannelSuffix.isNotEmpty()) ".$messageChannelSuffix" else ""
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.hubspot_flutter_chat.HubspotChatHostApi.configure$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { message, reply ->
            val args = message as List<Any?>
            val setupArg = args[0] as ChatSetupData
            api.configure(setupArg) { result: Result<Unit> ->
              val error = result.exceptionOrNull()
              if (error != null) {
                reply.reply(MessagesPigeonUtils.wrapError(error))
              } else {
                reply.reply(MessagesPigeonUtils.wrapResult(null))
              }
            }
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.hubspot_flutter_chat.HubspotChatHostApi.openChat$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { message, reply ->
            val args = message as List<Any?>
            val chatFlowArg = args[0] as String?
            api.openChat(chatFlowArg) { result: Result<Unit> ->
              val error = result.exceptionOrNull()
              if (error != null) {
                reply.reply(MessagesPigeonUtils.wrapError(error))
              } else {
                reply.reply(MessagesPigeonUtils.wrapResult(null))
              }
            }
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.hubspot_flutter_chat.HubspotChatHostApi.closeChat$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { _, reply ->
            api.closeChat{ result: Result<Unit> ->
              val error = result.exceptionOrNull()
              if (error != null) {
                reply.reply(MessagesPigeonUtils.wrapError(error))
              } else {
                reply.reply(MessagesPigeonUtils.wrapResult(null))
              }
            }
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.hubspot_flutter_chat.HubspotChatHostApi.setUserIdentity$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { message, reply ->
            val args = message as List<Any?>
            val identityArg = args[0] as VisitorIdentity
            api.setUserIdentity(identityArg) { result: Result<Unit> ->
              val error = result.exceptionOrNull()
              if (error != null) {
                reply.reply(MessagesPigeonUtils.wrapError(error))
              } else {
                reply.reply(MessagesPigeonUtils.wrapResult(null))
              }
            }
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.hubspot_flutter_chat.HubspotChatHostApi.setChatProperties$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { message, reply ->
            val args = message as List<Any?>
            val propertiesArg = args[0] as Map<String, String>
            api.setChatProperties(propertiesArg) { result: Result<Unit> ->
              val error = result.exceptionOrNull()
              if (error != null) {
                reply.reply(MessagesPigeonUtils.wrapError(error))
              } else {
                reply.reply(MessagesPigeonUtils.wrapResult(null))
              }
            }
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.hubspot_flutter_chat.HubspotChatHostApi.setPushToken$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { message, reply ->
            val args = message as List<Any?>
            val tokenArg = args[0] as String
            api.setPushToken(tokenArg) { result: Result<Unit> ->
              val error = result.exceptionOrNull()
              if (error != null) {
                reply.reply(MessagesPigeonUtils.wrapError(error))
              } else {
                reply.reply(MessagesPigeonUtils.wrapResult(null))
              }
            }
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.hubspot_flutter_chat.HubspotChatHostApi.handlePushNotification$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { message, reply ->
            val args = message as List<Any?>
            val dataArg = args[0] as Map<String, String>
            api.handlePushNotification(dataArg) { result: Result<Boolean> ->
              val error = result.exceptionOrNull()
              if (error != null) {
                reply.reply(MessagesPigeonUtils.wrapError(error))
              } else {
                val data = result.getOrNull()
                reply.reply(MessagesPigeonUtils.wrapResult(data))
              }
            }
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.hubspot_flutter_chat.HubspotChatHostApi.logout$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { _, reply ->
            api.logout{ result: Result<Unit> ->
              val error = result.exceptionOrNull()
              if (error != null) {
                reply.reply(MessagesPigeonUtils.wrapError(error))
              } else {
                reply.reply(MessagesPigeonUtils.wrapResult(null))
              }
            }
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
    }
  }
}
/**
 * Native -> Dart callbacks (chat events).
 *
 * NOTE: neither native SDK (Android com.hubspot.mobilesdk 1.0.x, iOS
 * HubspotMobileSDK 1.0.x) exposes an unread-message-count observer, so no
 * `onUnreadCountChanged` event is declared — it would be dead on both
 * platforms. Add it back only once the SDKs expose such an observer.
 *
 * Generated class from Pigeon that represents Flutter messages that can be called from Kotlin.
 */
class HubspotChatFlutterApi(private val binaryMessenger: BinaryMessenger, private val messageChannelSuffix: String = "") {
  companion object {
    /** The codec used by HubspotChatFlutterApi. */
    val codec: MessageCodec<Any?> by lazy {
      MessagesPigeonCodec()
    }
  }
  /**
   * A new inbound chat message arrived. Fired on both platforms when a HubSpot
   * chat push is handed to `handlePushNotification` (Android gates on
   * `HubspotManager.isHubspotNotification`).
   */
  fun onNewMessage(callback: (Result<Unit>) -> Unit)
{
    val separatedMessageChannelSuffix = if (messageChannelSuffix.isNotEmpty()) ".$messageChannelSuffix" else ""
    val channelName = "dev.flutter.pigeon.hubspot_flutter_chat.HubspotChatFlutterApi.onNewMessage$separatedMessageChannelSuffix"
    val channel = BasicMessageChannel<Any?>(binaryMessenger, channelName, codec)
    channel.send(null) {
      if (it is List<*>) {
        if (it.size > 1) {
          callback(Result.failure(FlutterError(it[0] as String, it[1] as String, it[2] as String?)))
        } else {
          callback(Result.success(Unit))
        }
      } else {
        callback(Result.failure(MessagesPigeonUtils.createConnectionError(channelName)))
      } 
    }
  }
  /** The chat UI was presented. */
  fun onChatOpened(callback: (Result<Unit>) -> Unit)
{
    val separatedMessageChannelSuffix = if (messageChannelSuffix.isNotEmpty()) ".$messageChannelSuffix" else ""
    val channelName = "dev.flutter.pigeon.hubspot_flutter_chat.HubspotChatFlutterApi.onChatOpened$separatedMessageChannelSuffix"
    val channel = BasicMessageChannel<Any?>(binaryMessenger, channelName, codec)
    channel.send(null) {
      if (it is List<*>) {
        if (it.size > 1) {
          callback(Result.failure(FlutterError(it[0] as String, it[1] as String, it[2] as String?)))
        } else {
          callback(Result.success(Unit))
        }
      } else {
        callback(Result.failure(MessagesPigeonUtils.createConnectionError(channelName)))
      } 
    }
  }
  /**
   * The chat UI was dismissed. **iOS only** — the Android SDK opens chat as a
   * separate Activity with no close callback, so Android never fires this.
   */
  fun onChatClosed(callback: (Result<Unit>) -> Unit)
{
    val separatedMessageChannelSuffix = if (messageChannelSuffix.isNotEmpty()) ".$messageChannelSuffix" else ""
    val channelName = "dev.flutter.pigeon.hubspot_flutter_chat.HubspotChatFlutterApi.onChatClosed$separatedMessageChannelSuffix"
    val channel = BasicMessageChannel<Any?>(binaryMessenger, channelName, codec)
    channel.send(null) {
      if (it is List<*>) {
        if (it.size > 1) {
          callback(Result.failure(FlutterError(it[0] as String, it[1] as String, it[2] as String?)))
        } else {
          callback(Result.success(Unit))
        }
      } else {
        callback(Result.failure(MessagesPigeonUtils.createConnectionError(channelName)))
      } 
    }
  }
}
