include: package:flutter_lints/flutter.yaml

analyzer:
  exclude:
    # Pigeon-generated; not our style to police.
    - lib/src/messages.g.dart
  errors:
    todo: ignore

linter:
  rules:
    prefer_single_quotes: true
    always_declare_return_types: true
