import 'dart:async';

import 'package:flutter/foundation.dart';

import 'chat_config.dart';
import 'messages.g.dart';

/// A Flutter bridge over HubSpot's native iOS & Android mobile chat SDKs.
///
/// Usage:
/// ```dart
/// final chat = HubspotChat.instance;
/// await chat.configure(const HubspotChatConfig(portalId: '1234567'));
///
/// // Optional: identify a logged-in visitor. The identityToken is minted on
/// // your backend (POST /visitor-identification/v3/tokens/create) — hubspot_flutter
/// // does not mint it.
/// await chat.setUserIdentity(email: 'ada@example.com', identityToken: token);
///
/// await chat.open();
/// chat.onNewMessage.listen((_) => refreshBadge());
/// ```
///
/// The type-safe platform channel is generated by Pigeon
/// ([HubspotChatHostApi] / [HubspotChatFlutterApi]); this class wraps it in an
/// ergonomic API and turns native callbacks into broadcast [Stream]s.
class HubspotChat {
  /// Creates an instance.
  ///
  /// [hostApi] is injectable for testing; production code should use
  /// [instance]. Set [registerEventHandler] to `false` in unit tests that do
  /// not have a Flutter binding set up.
  HubspotChat({HubspotChatHostApi? hostApi, bool registerEventHandler = true})
    : _api = hostApi ?? HubspotChatHostApi() {
    _eventHandler = _ChatEventHandler(this);
    if (registerEventHandler) {
      HubspotChatFlutterApi.setUp(_eventHandler);
    }
  }

  /// The shared instance used by apps.
  static final HubspotChat instance = HubspotChat();

  final HubspotChatHostApi _api;
  late final _ChatEventHandler _eventHandler;

  final StreamController<void> _newMessage = StreamController<void>.broadcast();
  final StreamController<bool> _visibility = StreamController<bool>.broadcast();

  bool _configured = false;

  /// Whether [configure] has completed successfully.
  bool get isConfigured => _configured;

  /// Emits whenever a new inbound chat message arrives.
  ///
  /// Fired when a HubSpot chat push is handed to [handlePushNotification]
  /// (Android only fires it when the SDK confirms the push is HubSpot's).
  ///
  /// > There is intentionally **no unread-count stream**: neither the Android
  /// > nor iOS HubSpot SDK (1.0.x) exposes an unread-message-count observer, so
  /// > such a stream would be dead. It will be added when the SDKs support it.
  Stream<void> get onNewMessage => _newMessage.stream;

  /// Emits `true` when the chat UI is presented and `false` when dismissed.
  ///
  /// > **Platform asymmetry:** iOS emits both `true` and `false`. **Android only
  /// > emits `true`** — the Android SDK opens chat as a separate Activity with
  /// > no close callback, so a `false` (dismissed) event never fires there.
  Stream<bool> get onVisibilityChanged => _visibility.stream;

  /// The Pigeon Flutter-API receiver, exposed only for tests to simulate native
  /// callbacks.
  @visibleForTesting
  HubspotChatFlutterApi get eventReceiver => _eventHandler;

  /// Initialises the native chat SDK. Must be awaited before any other call.
  ///
  /// Note that the native SDKs load `portalId` / `hublet` / `environment` from
  /// the app's bundled native config file, not from [config] — see
  /// [HubspotChatConfig] and the README's *Native setup*.
  Future<void> configure(HubspotChatConfig config) async {
    await _api.configure(config.toPigeon());
    _configured = true;
  }

  /// Presents the chat UI. [chatFlow] overrides the configured default.
  Future<void> open({String? chatFlow}) {
    _assertConfigured();
    return _api.openChat(chatFlow);
  }

  /// Dismisses the chat UI.
  Future<void> close() {
    _assertConfigured();
    return _api.closeChat();
  }

  /// Identifies the current visitor.
  ///
  /// [identityToken] must be minted server-side; see the class docs.
  Future<void> setUserIdentity({
    required String email,
    required String identityToken,
  }) {
    _assertConfigured();
    return _api.setUserIdentity(
      VisitorIdentity(email: email, identityToken: identityToken),
    );
  }

  /// Attaches custom properties to subsequent conversations.
  Future<void> setChatProperties(Map<String, String> properties) {
    _assertConfigured();
    return _api.setChatProperties(properties);
  }

  /// Registers the device push token (FCM on Android, APNs on iOS).
  Future<void> setPushToken(String token) {
    _assertConfigured();
    return _api.setPushToken(token);
  }

  /// Asks the native SDK whether a push payload is a HubSpot chat notification,
  /// returning `true` only when it is (so your app can stop processing it).
  ///
  /// > **Platform asymmetry — read before relying on the return value:**
  /// > * **Android** is authoritative: it checks
  /// >   `HubspotManager.isHubspotNotification` and returns `true`/`false`
  /// >   accordingly (emitting [onNewMessage] on `true`).
  /// > * **iOS** returns a conservative `false` for every payload and emits no
  /// >   event — the iOS SDK 1.0.x exposes no "is this ours" check. Do **not**
  /// >   use the iOS return value to decide whether to suppress your own
  /// >   notification handling (it would never suppress). Integrate HubSpot
  /// >   chat pushes on iOS via HubSpot's AppDelegate flow instead. This will
  /// >   become authoritative once the iOS SDK adds a detection API.
  Future<bool> handlePushNotification(Map<String, String> data) {
    _assertConfigured();
    return _api.handlePushNotification(data);
  }

  /// Clears the identified visitor and cached conversation state.
  Future<void> logout() {
    _assertConfigured();
    return _api.logout();
  }

  /// Releases the event stream controllers. Call when the bridge is disposed
  /// (rarely needed for the singleton).
  Future<void> dispose() async {
    await _newMessage.close();
    await _visibility.close();
  }

  void _assertConfigured() {
    if (!_configured) {
      throw StateError(
        'HubspotChat.configure() must be awaited before using the chat bridge.',
      );
    }
  }

  void _emitNewMessage() {
    if (!_newMessage.isClosed) _newMessage.add(null);
  }

  void _emitVisibility(bool visible) {
    if (!_visibility.isClosed) _visibility.add(visible);
  }
}

/// Receives native → Dart chat events and fans them into [HubspotChat]'s
/// broadcast streams.
class _ChatEventHandler implements HubspotChatFlutterApi {
  _ChatEventHandler(this._chat);

  final HubspotChat _chat;

  @override
  void onNewMessage() => _chat._emitNewMessage();

  @override
  void onChatOpened() => _chat._emitVisibility(true);

  @override
  void onChatClosed() => _chat._emitVisibility(false);
}
