// Autogenerated from Pigeon (v27.3.0), do not edit directly.
// See also: https://pub.dev/packages/pigeon
// ignore_for_file: unused_import, unused_shown_name
// ignore_for_file: type=lint

import 'dart:async';
import 'dart:typed_data' show Float64List, Int32List, Int64List;

import 'package:flutter/services.dart';
import 'package:meta/meta.dart' show immutable, protected, visibleForTesting;

Object? _extractReplyValueOrThrow(
    List<Object?>? replyList,
    String channelName, {
    required bool isNullValid,
}) {
  if (replyList == null) {
    throw PlatformException(
      code: 'channel-error',
      message: 'Unable to establish connection on channel: "$channelName".',
    );
  } else if (replyList.length > 1) {
    throw PlatformException(
      code: replyList[0]! as String,
      message: replyList[1] as String?,
      details: replyList[2],
    );
  } else if (!isNullValid && (replyList.isNotEmpty && replyList[0] == null)) {
    throw PlatformException(
      code: 'null-error',
      message: 'Host platform returned null value for non-null return value.',
    );
  }
  return replyList.firstOrNull;
}


List<Object?> wrapResponse({Object? result, PlatformException? error, bool empty = false}) {
  if (empty) {
    return <Object?>[];
  }
  if (error == null) {
    return <Object?>[result];
  }
  return <Object?>[error.code, error.message, error.details];
}
bool _deepEquals(Object? a, Object? b) {
  if (identical(a, b)) {
    return true;
  }
  if (a is double && b is double) {
    if (a.isNaN && b.isNaN) {
      return true;
    }
    return a == b;
  }
  if (a is List && b is List) {
    return a.length == b.length &&
        a.indexed
            .every(((int, dynamic) item) => _deepEquals(item.$2, b[item.$1]));
  }
  if (a is Map && b is Map) {
    if (a.length != b.length) {
      return false;
    }
    for (final MapEntry<Object?, Object?> entryA in a.entries) {
      bool found = false;
      for (final MapEntry<Object?, Object?> entryB in b.entries) {
        if (_deepEquals(entryA.key, entryB.key)) {
          if (_deepEquals(entryA.value, entryB.value)) {
            found = true;
            break;
          } else {
            return false;
          }
        }
      }
      if (!found) {
        return false;
      }
    }
    return true;
  }
  return a == b;
}

int _deepHash(Object? value) {
  if (value is List) {
    return Object.hashAll(value.map(_deepHash));
  }
  if (value is Map) {
    int result = 0;
    for (final MapEntry<Object?, Object?> entry in value.entries) {
      result += (_deepHash(entry.key) * 31) ^ _deepHash(entry.value);
    }
    return result;
  }
  if (value is double && value.isNaN) {
    // Normalize NaN to a consistent hash.
    return 0x7FF8000000000000.hashCode;
  }
  if (value is double && value == 0.0) {
    // Normalize -0.0 to 0.0 so they have the same hash code.
    return 0.0.hashCode;
  }
  return value.hashCode;
}


/// Configuration for the HubSpot mobile chat SDK.
class ChatSetupData {
  ChatSetupData({
    required this.portalId,
    this.hublet,
    this.defaultChatFlow,
    this.environment,
    this.enableLogging = false,
  });

  /// The public HubSpot portal / Hub ID.
  String portalId;

  /// The HubSpot hublet (data-hosting region), e.g. `na1` / `eu1`.
  String? hublet;

  /// The default chatflow to open when none is specified.
  String? defaultChatFlow;

  /// The HubSpot environment (`PROD` by default).
  String? environment;

  /// Whether to enable verbose native SDK logging.
  bool enableLogging;

  List<Object?> _toList() {
    return <Object?>[
      portalId,
      hublet,
      defaultChatFlow,
      environment,
      enableLogging,
    ];
  }

  Object encode() {
    return _toList();  }

  static ChatSetupData decode(Object result) {
    result as List<Object?>;
    return ChatSetupData(
      portalId: result[0]! as String,
      hublet: result[1] as String?,
      defaultChatFlow: result[2] as String?,
      environment: result[3] as String?,
      enableLogging: result[4]! as bool,
    );
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  bool operator ==(Object other) {
    if (other is! ChatSetupData || other.runtimeType != runtimeType) {
      return false;
    }
    if (identical(this, other)) {
      return true;
    }
    return _deepEquals(portalId, other.portalId) && _deepEquals(hublet, other.hublet) && _deepEquals(defaultChatFlow, other.defaultChatFlow) && _deepEquals(environment, other.environment) && _deepEquals(enableLogging, other.enableLogging);
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  int get hashCode => _deepHash(<Object?>[runtimeType, ..._toList()]);

  @override
  String toString() {
    return 'ChatSetupData(portalId: $portalId, hublet: $hublet, defaultChatFlow: $defaultChatFlow, environment: $environment, enableLogging: $enableLogging)';
  }
}

/// A visitor identity for authenticated chat.
///
/// The [identityToken] is minted **server-side** via
/// `POST /visitor-identification/v3/tokens/create`; the client only consumes it.
class VisitorIdentity {
  VisitorIdentity({
    required this.email,
    required this.identityToken,
  });

  /// The visitor's email address.
  String email;

  /// The server-minted visitor-identification token.
  String identityToken;

  List<Object?> _toList() {
    return <Object?>[
      email,
      identityToken,
    ];
  }

  Object encode() {
    return _toList();  }

  static VisitorIdentity decode(Object result) {
    result as List<Object?>;
    return VisitorIdentity(
      email: result[0]! as String,
      identityToken: result[1]! as String,
    );
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  bool operator ==(Object other) {
    if (other is! VisitorIdentity || other.runtimeType != runtimeType) {
      return false;
    }
    if (identical(this, other)) {
      return true;
    }
    return _deepEquals(email, other.email) && _deepEquals(identityToken, other.identityToken);
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  int get hashCode => _deepHash(<Object?>[runtimeType, ..._toList()]);

  @override
  String toString() {
    return 'VisitorIdentity(email: $email, identityToken: $identityToken)';
  }
}


class _PigeonCodec extends StandardMessageCodec {
  const _PigeonCodec();
  @override
  void writeValue(WriteBuffer buffer, Object? value) {
    if (value is int) {
      buffer.putUint8(4);
      buffer.putInt64(value);
    }    else if (value is ChatSetupData) {
      buffer.putUint8(129);
      writeValue(buffer, value.encode());
    }    else if (value is VisitorIdentity) {
      buffer.putUint8(130);
      writeValue(buffer, value.encode());
    } else {
      super.writeValue(buffer, value);
    }
  }

  @override
  Object? readValueOfType(int type, ReadBuffer buffer) {
    switch (type) {
      case 129:
        return ChatSetupData.decode(readValue(buffer)!);
      case 130:
        return VisitorIdentity.decode(readValue(buffer)!);
      default:
        return super.readValueOfType(type, buffer);
    }
  }
}

/// Dart -> native calls.
class HubspotChatHostApi {
  /// Constructor for [HubspotChatHostApi]. The [binaryMessenger] named argument is
  /// available for dependency injection. If it is left null, the default
  /// BinaryMessenger will be used which routes to the host platform.
  HubspotChatHostApi({BinaryMessenger? binaryMessenger, String messageChannelSuffix = ''})
      : pigeonVar_binaryMessenger = binaryMessenger,
        pigeonVar_messageChannelSuffix = messageChannelSuffix.isNotEmpty ? '.$messageChannelSuffix' : '';
  final BinaryMessenger? pigeonVar_binaryMessenger;

  static const MessageCodec<Object?> pigeonChannelCodec = _PigeonCodec();

  final String pigeonVar_messageChannelSuffix;

  /// Initialises the native HubSpot chat SDK. Must be called before any other
  /// method.
  Future<void> configure(ChatSetupData setup) async {
    final pigeonVar_channelName = 'dev.flutter.pigeon.hubspot_flutter_chat.HubspotChatHostApi.configure$pigeonVar_messageChannelSuffix';
    final pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final Future<Object?> pigeonVar_sendFuture = pigeonVar_channel.send(<Object?>[setup]);
    final pigeonVar_replyList = await pigeonVar_sendFuture as List<Object?>?;

    _extractReplyValueOrThrow(
        pigeonVar_replyList,
        pigeonVar_channelName,
        isNullValid: true,
    )
    ;
  }

  /// Presents the chat UI, optionally targeting a specific [chatFlow].
  Future<void> openChat(String? chatFlow) async {
    final pigeonVar_channelName = 'dev.flutter.pigeon.hubspot_flutter_chat.HubspotChatHostApi.openChat$pigeonVar_messageChannelSuffix';
    final pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final Future<Object?> pigeonVar_sendFuture = pigeonVar_channel.send(<Object?>[chatFlow]);
    final pigeonVar_replyList = await pigeonVar_sendFuture as List<Object?>?;

    _extractReplyValueOrThrow(
        pigeonVar_replyList,
        pigeonVar_channelName,
        isNullValid: true,
    )
    ;
  }

  /// Dismisses the chat UI if it is visible.
  Future<void> closeChat() async {
    final pigeonVar_channelName = 'dev.flutter.pigeon.hubspot_flutter_chat.HubspotChatHostApi.closeChat$pigeonVar_messageChannelSuffix';
    final pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final Future<Object?> pigeonVar_sendFuture = pigeonVar_channel.send(null);
    final pigeonVar_replyList = await pigeonVar_sendFuture as List<Object?>?;

    _extractReplyValueOrThrow(
        pigeonVar_replyList,
        pigeonVar_channelName,
        isNullValid: true,
    )
    ;
  }

  /// Associates the current session with an identified visitor.
  Future<void> setUserIdentity(VisitorIdentity identity) async {
    final pigeonVar_channelName = 'dev.flutter.pigeon.hubspot_flutter_chat.HubspotChatHostApi.setUserIdentity$pigeonVar_messageChannelSuffix';
    final pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final Future<Object?> pigeonVar_sendFuture = pigeonVar_channel.send(<Object?>[identity]);
    final pigeonVar_replyList = await pigeonVar_sendFuture as List<Object?>?;

    _extractReplyValueOrThrow(
        pigeonVar_replyList,
        pigeonVar_channelName,
        isNullValid: true,
    )
    ;
  }

  /// Sets custom chat properties attached to subsequent conversations.
  Future<void> setChatProperties(Map<String, String> properties) async {
    final pigeonVar_channelName = 'dev.flutter.pigeon.hubspot_flutter_chat.HubspotChatHostApi.setChatProperties$pigeonVar_messageChannelSuffix';
    final pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final Future<Object?> pigeonVar_sendFuture = pigeonVar_channel.send(<Object?>[properties]);
    final pigeonVar_replyList = await pigeonVar_sendFuture as List<Object?>?;

    _extractReplyValueOrThrow(
        pigeonVar_replyList,
        pigeonVar_channelName,
        isNullValid: true,
    )
    ;
  }

  /// Registers the device push token (FCM on Android, APNs on iOS) so HubSpot
  /// can deliver chat push notifications.
  Future<void> setPushToken(String token) async {
    final pigeonVar_channelName = 'dev.flutter.pigeon.hubspot_flutter_chat.HubspotChatHostApi.setPushToken$pigeonVar_messageChannelSuffix';
    final pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final Future<Object?> pigeonVar_sendFuture = pigeonVar_channel.send(<Object?>[token]);
    final pigeonVar_replyList = await pigeonVar_sendFuture as List<Object?>?;

    _extractReplyValueOrThrow(
        pigeonVar_replyList,
        pigeonVar_channelName,
        isNullValid: true,
    )
    ;
  }

  /// Asks the native SDK whether it recognises and will handle a push payload.
  /// Returns true if the payload was a HubSpot chat notification.
  Future<bool> handlePushNotification(Map<String, String> data) async {
    final pigeonVar_channelName = 'dev.flutter.pigeon.hubspot_flutter_chat.HubspotChatHostApi.handlePushNotification$pigeonVar_messageChannelSuffix';
    final pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final Future<Object?> pigeonVar_sendFuture = pigeonVar_channel.send(<Object?>[data]);
    final pigeonVar_replyList = await pigeonVar_sendFuture as List<Object?>?;

    final Object? pigeonVar_replyValue = _extractReplyValueOrThrow(
        pigeonVar_replyList,
        pigeonVar_channelName,
        isNullValid: false,
    )
    ;
    return pigeonVar_replyValue! as bool;
  }

  /// Clears the identified visitor and cached conversation state.
  Future<void> logout() async {
    final pigeonVar_channelName = 'dev.flutter.pigeon.hubspot_flutter_chat.HubspotChatHostApi.logout$pigeonVar_messageChannelSuffix';
    final pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final Future<Object?> pigeonVar_sendFuture = pigeonVar_channel.send(null);
    final pigeonVar_replyList = await pigeonVar_sendFuture as List<Object?>?;

    _extractReplyValueOrThrow(
        pigeonVar_replyList,
        pigeonVar_channelName,
        isNullValid: true,
    )
    ;
  }
}

/// Native -> Dart callbacks (chat events).
///
/// NOTE: neither native SDK (Android com.hubspot.mobilesdk 1.0.x, iOS
/// HubspotMobileSDK 1.0.x) exposes an unread-message-count observer, so no
/// `onUnreadCountChanged` event is declared — it would be dead on both
/// platforms. Add it back only once the SDKs expose such an observer.
abstract class HubspotChatFlutterApi {
  static const MessageCodec<Object?> pigeonChannelCodec = _PigeonCodec();

  /// A new inbound chat message arrived. Fired on both platforms when a HubSpot
  /// chat push is handed to `handlePushNotification` (Android gates on
  /// `HubspotManager.isHubspotNotification`).
  void onNewMessage();

  /// The chat UI was presented.
  void onChatOpened();

  /// The chat UI was dismissed. **iOS only** — the Android SDK opens chat as a
  /// separate Activity with no close callback, so Android never fires this.
  void onChatClosed();

  static void setUp(HubspotChatFlutterApi? api, {BinaryMessenger? binaryMessenger, String messageChannelSuffix = '',}) {
    messageChannelSuffix = messageChannelSuffix.isNotEmpty ? '.$messageChannelSuffix' : '';
    {
      final pigeonVar_channel = BasicMessageChannel<Object?>(
          'dev.flutter.pigeon.hubspot_flutter_chat.HubspotChatFlutterApi.onNewMessage$messageChannelSuffix', pigeonChannelCodec,
          binaryMessenger: binaryMessenger);
      if (api == null) {
        pigeonVar_channel.setMessageHandler(null);
      } else {
        pigeonVar_channel.setMessageHandler((Object? message) async {
          try {
            api.onNewMessage();
            return wrapResponse(empty: true);
          } on PlatformException catch (e) {
            return wrapResponse(error: e);
          }          catch (e) {
            return wrapResponse(error: PlatformException(code: 'error', message: e.toString()));
          }
        });
      }
    }
    {
      final pigeonVar_channel = BasicMessageChannel<Object?>(
          'dev.flutter.pigeon.hubspot_flutter_chat.HubspotChatFlutterApi.onChatOpened$messageChannelSuffix', pigeonChannelCodec,
          binaryMessenger: binaryMessenger);
      if (api == null) {
        pigeonVar_channel.setMessageHandler(null);
      } else {
        pigeonVar_channel.setMessageHandler((Object? message) async {
          try {
            api.onChatOpened();
            return wrapResponse(empty: true);
          } on PlatformException catch (e) {
            return wrapResponse(error: e);
          }          catch (e) {
            return wrapResponse(error: PlatformException(code: 'error', message: e.toString()));
          }
        });
      }
    }
    {
      final pigeonVar_channel = BasicMessageChannel<Object?>(
          'dev.flutter.pigeon.hubspot_flutter_chat.HubspotChatFlutterApi.onChatClosed$messageChannelSuffix', pigeonChannelCodec,
          binaryMessenger: binaryMessenger);
      if (api == null) {
        pigeonVar_channel.setMessageHandler(null);
      } else {
        pigeonVar_channel.setMessageHandler((Object? message) async {
          try {
            api.onChatClosed();
            return wrapResponse(empty: true);
          } on PlatformException catch (e) {
            return wrapResponse(error: e);
          }          catch (e) {
            return wrapResponse(error: PlatformException(code: 'error', message: e.toString()));
          }
        });
      }
    }
  }
}
