// Autogenerated from Pigeon (v27.3.0), do not edit directly.
// See also: https://pub.dev/packages/pigeon

import Foundation

#if os(iOS)
  import Flutter
#elseif os(macOS)
  import FlutterMacOS
#else
  #error("Unsupported platform.")
#endif

/// Error class for passing custom error details to Dart side.
final class PigeonError: Error {
  let code: String
  let message: String?
  let details: Sendable?

  init(code: String, message: String?, details: Sendable?) {
    self.code = code
    self.message = message
    self.details = details
  }

  var localizedDescription: String {
    return
      "PigeonError(code: \(code), message: \(message ?? "<nil>"), details: \(details ?? "<nil>")"
  }
}

private func wrapResult(_ result: Any?) -> [Any?] {
  return [result]
}

private func wrapError(_ error: Any) -> [Any?] {
  if let pigeonError = error as? PigeonError {
    return [
      pigeonError.code,
      pigeonError.message,
      pigeonError.details,
    ]
  }
  if let flutterError = error as? FlutterError {
    return [
      flutterError.code,
      flutterError.message,
      flutterError.details,
    ]
  }
  return [
    "\(error)",
    "\(Swift.type(of: error))",
    "Stacktrace: \(Thread.callStackSymbols)",
  ]
}

private func createConnectionError(withChannelName channelName: String) -> PigeonError {
  return PigeonError(code: "channel-error", message: "Unable to establish connection on channel: '\(channelName)'.", details: "")
}

enum MessagesPigeonInternal {
  static func isNullish(_ value: Any?) -> Bool {
    guard let innerValue = value else {
      return true
    }

    if case Optional<Any>.some(Optional<Any>.none) = value {
      return true
    }

    return innerValue is NSNull
  }
  static func doubleEquals(_ lhs: Double, _ rhs: Double) -> Bool {
    return (lhs.isNaN && rhs.isNaN) || lhs == rhs
  }

  static func doubleHash(_ value: Double, _ hasher: inout Hasher) {
    if value.isNaN {
      hasher.combine(0x7FF8000000000000)
    } else {
      // Normalize -0.0 to 0.0
      hasher.combine(value == 0 ? 0 : value)
    }
  }

  static func deepEquals(_ lhs: Any?, _ rhs: Any?) -> Bool {
    let cleanLhs = nilOrValue(lhs) as Any?
    let cleanRhs = nilOrValue(rhs) as Any?
    switch (cleanLhs, cleanRhs) {
    case (nil, nil):
      return true

    case (nil, _), (_, nil):
      return false

    case (let lhs as AnyObject, let rhs as AnyObject) where lhs === rhs:
      return true

    case is (Void, Void):
      return true

    case (let lhsArray, let rhsArray) as ([Any?], [Any?]):
      guard lhsArray.count == rhsArray.count else { return false }
      for (index, element) in lhsArray.enumerated() {
        if !deepEquals(element, rhsArray[index]) {
          return false
        }
      }
      return true

    case (let lhsArray, let rhsArray) as ([Double], [Double]):
      guard lhsArray.count == rhsArray.count else { return false }
      for (index, element) in lhsArray.enumerated() {
        if !doubleEquals(element, rhsArray[index]) {
          return false
        }
      }
      return true

    case (let lhsDictionary, let rhsDictionary) as ([AnyHashable: Any?], [AnyHashable: Any?]):
      guard lhsDictionary.count == rhsDictionary.count else { return false }
      for (lhsKey, lhsValue) in lhsDictionary {
        var found = false
        for (rhsKey, rhsValue) in rhsDictionary {
          if deepEquals(lhsKey, rhsKey) {
            if deepEquals(lhsValue, rhsValue) {
              found = true
              break
            } else {
              return false
            }
          }
        }
        if !found { return false }
      }
      return true

    case (let lhs as Double, let rhs as Double):
      return doubleEquals(lhs, rhs)

    case (let lhsHashable, let rhsHashable) as (AnyHashable, AnyHashable):
      return lhsHashable == rhsHashable

    default:
      return false
    }
  }

  static func deepHash(value: Any?, hasher: inout Hasher) {
    let cleanValue = nilOrValue(value) as Any?
    if let cleanValue = cleanValue {
      if let doubleValue = cleanValue as? Double {
        doubleHash(doubleValue, &hasher)
      } else if let valueList = cleanValue as? [Any?] {
        for item in valueList {
          deepHash(value: item, hasher: &hasher)
        }
      } else if let valueList = cleanValue as? [Double] {
        for item in valueList {
          doubleHash(item, &hasher)
        }
      } else if let valueDict = cleanValue as? [AnyHashable: Any?] {
        var result = 0
        for (key, value) in valueDict {
          var entryKeyHasher = Hasher()
          deepHash(value: key, hasher: &entryKeyHasher)
          var entryValueHasher = Hasher()
          deepHash(value: value, hasher: &entryValueHasher)
          result = result &+ ((entryKeyHasher.finalize() &* 31) ^ entryValueHasher.finalize())
        }
        hasher.combine(result)
      } else if let hashableValue = cleanValue as? AnyHashable {
        hasher.combine(hashableValue)
      } else {
        hasher.combine(String(describing: cleanValue))
      }
    } else {
      hasher.combine(0)
    }
  }

}

private func nilOrValue<T>(_ value: Any?) -> T? {
  if value is NSNull { return nil }
  return value as! T?
}


/// Configuration for the HubSpot mobile chat SDK.
///
/// Generated class from Pigeon that represents data sent in messages.
struct ChatSetupData: Hashable, CustomStringConvertible {
  /// The public HubSpot portal / Hub ID.
  var portalId: String
  /// The HubSpot hublet (data-hosting region), e.g. `na1` / `eu1`.
  var hublet: String? = nil
  /// The default chatflow to open when none is specified.
  var defaultChatFlow: String? = nil
  /// The HubSpot environment (`PROD` by default).
  var environment: String? = nil
  /// Whether to enable verbose native SDK logging.
  var enableLogging: Bool


  // swift-format-ignore: AlwaysUseLowerCamelCase
  static func fromList(_ pigeonVar_list: [Any?]) -> ChatSetupData? {
    let portalId = pigeonVar_list[0] as! String
    let hublet: String? = nilOrValue(pigeonVar_list[1])
    let defaultChatFlow: String? = nilOrValue(pigeonVar_list[2])
    let environment: String? = nilOrValue(pigeonVar_list[3])
    let enableLogging = pigeonVar_list[4] as! Bool

    return ChatSetupData(
      portalId: portalId,
      hublet: hublet,
      defaultChatFlow: defaultChatFlow,
      environment: environment,
      enableLogging: enableLogging
    )
  }
  func toList() -> [Any?] {
    return [
      portalId,
      hublet,
      defaultChatFlow,
      environment,
      enableLogging,
    ]
  }
  static func == (lhs: ChatSetupData, rhs: ChatSetupData) -> Bool {
    if Swift.type(of: lhs) != Swift.type(of: rhs) {
      return false
    }
    return MessagesPigeonInternal.deepEquals(lhs.portalId, rhs.portalId) && MessagesPigeonInternal.deepEquals(lhs.hublet, rhs.hublet) && MessagesPigeonInternal.deepEquals(lhs.defaultChatFlow, rhs.defaultChatFlow) && MessagesPigeonInternal.deepEquals(lhs.environment, rhs.environment) && MessagesPigeonInternal.deepEquals(lhs.enableLogging, rhs.enableLogging)
  }

  func hash(into hasher: inout Hasher) {
    hasher.combine("ChatSetupData")
    MessagesPigeonInternal.deepHash(value: portalId, hasher: &hasher)
    MessagesPigeonInternal.deepHash(value: hublet, hasher: &hasher)
    MessagesPigeonInternal.deepHash(value: defaultChatFlow, hasher: &hasher)
    MessagesPigeonInternal.deepHash(value: environment, hasher: &hasher)
    MessagesPigeonInternal.deepHash(value: enableLogging, hasher: &hasher)
  }

  public var description: String {
    return "ChatSetupData(portalId: \(String(describing: portalId)), hublet: \(String(describing: hublet)), defaultChatFlow: \(String(describing: defaultChatFlow)), environment: \(String(describing: environment)), enableLogging: \(String(describing: enableLogging)))"
  }
}

/// A visitor identity for authenticated chat.
///
/// The [identityToken] is minted **server-side** via
/// `POST /visitor-identification/v3/tokens/create`; the client only consumes it.
///
/// Generated class from Pigeon that represents data sent in messages.
struct VisitorIdentity: Hashable, CustomStringConvertible {
  /// The visitor's email address.
  var email: String
  /// The server-minted visitor-identification token.
  var identityToken: String


  // swift-format-ignore: AlwaysUseLowerCamelCase
  static func fromList(_ pigeonVar_list: [Any?]) -> VisitorIdentity? {
    let email = pigeonVar_list[0] as! String
    let identityToken = pigeonVar_list[1] as! String

    return VisitorIdentity(
      email: email,
      identityToken: identityToken
    )
  }
  func toList() -> [Any?] {
    return [
      email,
      identityToken,
    ]
  }
  static func == (lhs: VisitorIdentity, rhs: VisitorIdentity) -> Bool {
    if Swift.type(of: lhs) != Swift.type(of: rhs) {
      return false
    }
    return MessagesPigeonInternal.deepEquals(lhs.email, rhs.email) && MessagesPigeonInternal.deepEquals(lhs.identityToken, rhs.identityToken)
  }

  func hash(into hasher: inout Hasher) {
    hasher.combine("VisitorIdentity")
    MessagesPigeonInternal.deepHash(value: email, hasher: &hasher)
    MessagesPigeonInternal.deepHash(value: identityToken, hasher: &hasher)
  }

  public var description: String {
    return "VisitorIdentity(email: \(String(describing: email)), identityToken: \(String(describing: identityToken)))"
  }
}

private class MessagesPigeonCodecReader: FlutterStandardReader {
  override func readValue(ofType type: UInt8) -> Any? {
    switch type {
    case 129:
      return ChatSetupData.fromList(self.readValue() as! [Any?])
    case 130:
      return VisitorIdentity.fromList(self.readValue() as! [Any?])
    default:
      return super.readValue(ofType: type)
    }
  }
}

private class MessagesPigeonCodecWriter: FlutterStandardWriter {
  override func writeValue(_ value: Any) {
    if let value = value as? ChatSetupData {
      super.writeByte(129)
      super.writeValue(value.toList())
    } else if let value = value as? VisitorIdentity {
      super.writeByte(130)
      super.writeValue(value.toList())
    } else {
      super.writeValue(value)
    }
  }
}

private class MessagesPigeonCodecReaderWriter: FlutterStandardReaderWriter {
  override func reader(with data: Data) -> FlutterStandardReader {
    return MessagesPigeonCodecReader(data: data)
  }

  override func writer(with data: NSMutableData) -> FlutterStandardWriter {
    return MessagesPigeonCodecWriter(data: data)
  }
}

class MessagesPigeonCodec: FlutterStandardMessageCodec, @unchecked Sendable {
  static let shared = MessagesPigeonCodec(readerWriter: MessagesPigeonCodecReaderWriter())
}


/// Dart -> native calls.
///
/// Generated protocol from Pigeon that represents a handler of messages from Flutter.
protocol HubspotChatHostApi {
  /// Initialises the native HubSpot chat SDK. Must be called before any other
  /// method.
  func configure(setup: ChatSetupData, completion: @escaping (Result<Void, Error>) -> Void)
  /// Presents the chat UI, optionally targeting a specific [chatFlow].
  func openChat(chatFlow: String?, completion: @escaping (Result<Void, Error>) -> Void)
  /// Dismisses the chat UI if it is visible.
  func closeChat(completion: @escaping (Result<Void, Error>) -> Void)
  /// Associates the current session with an identified visitor.
  func setUserIdentity(identity: VisitorIdentity, completion: @escaping (Result<Void, Error>) -> Void)
  /// Sets custom chat properties attached to subsequent conversations.
  func setChatProperties(properties: [String: String], completion: @escaping (Result<Void, Error>) -> Void)
  /// Registers the device push token (FCM on Android, APNs on iOS) so HubSpot
  /// can deliver chat push notifications.
  func setPushToken(token: String, completion: @escaping (Result<Void, Error>) -> Void)
  /// Asks the native SDK whether it recognises and will handle a push payload.
  /// Returns true if the payload was a HubSpot chat notification.
  func handlePushNotification(data: [String: String], completion: @escaping (Result<Bool, Error>) -> Void)
  /// Clears the identified visitor and cached conversation state.
  func logout(completion: @escaping (Result<Void, Error>) -> Void)
}

/// Generated setup class from Pigeon to handle messages through the `binaryMessenger`.
class HubspotChatHostApiSetup {
  static var codec: FlutterStandardMessageCodec { MessagesPigeonCodec.shared }
  /// Sets up an instance of `HubspotChatHostApi` to handle messages through the `binaryMessenger`.
  static func setUp(binaryMessenger: FlutterBinaryMessenger, api: HubspotChatHostApi?, messageChannelSuffix: String = "") {
    let channelSuffix = messageChannelSuffix.count > 0 ? ".\(messageChannelSuffix)" : ""
    /// Initialises the native HubSpot chat SDK. Must be called before any other
    /// method.
    let configureChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.hubspot_flutter_chat.HubspotChatHostApi.configure\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      configureChannel.setMessageHandler { message, reply in
        let args = message as! [Any?]
        let setupArg = args[0] as! ChatSetupData
        api.configure(setup: setupArg) { result in
          switch result {
          case .success:
            reply(wrapResult(nil))
          case .failure(let error):
            reply(wrapError(error))
          }
        }
      }
    } else {
      configureChannel.setMessageHandler(nil)
    }
    /// Presents the chat UI, optionally targeting a specific [chatFlow].
    let openChatChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.hubspot_flutter_chat.HubspotChatHostApi.openChat\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      openChatChannel.setMessageHandler { message, reply in
        let args = message as! [Any?]
        let chatFlowArg: String? = nilOrValue(args[0])
        api.openChat(chatFlow: chatFlowArg) { result in
          switch result {
          case .success:
            reply(wrapResult(nil))
          case .failure(let error):
            reply(wrapError(error))
          }
        }
      }
    } else {
      openChatChannel.setMessageHandler(nil)
    }
    /// Dismisses the chat UI if it is visible.
    let closeChatChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.hubspot_flutter_chat.HubspotChatHostApi.closeChat\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      closeChatChannel.setMessageHandler { _, reply in
        api.closeChat { result in
          switch result {
          case .success:
            reply(wrapResult(nil))
          case .failure(let error):
            reply(wrapError(error))
          }
        }
      }
    } else {
      closeChatChannel.setMessageHandler(nil)
    }
    /// Associates the current session with an identified visitor.
    let setUserIdentityChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.hubspot_flutter_chat.HubspotChatHostApi.setUserIdentity\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      setUserIdentityChannel.setMessageHandler { message, reply in
        let args = message as! [Any?]
        let identityArg = args[0] as! VisitorIdentity
        api.setUserIdentity(identity: identityArg) { result in
          switch result {
          case .success:
            reply(wrapResult(nil))
          case .failure(let error):
            reply(wrapError(error))
          }
        }
      }
    } else {
      setUserIdentityChannel.setMessageHandler(nil)
    }
    /// Sets custom chat properties attached to subsequent conversations.
    let setChatPropertiesChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.hubspot_flutter_chat.HubspotChatHostApi.setChatProperties\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      setChatPropertiesChannel.setMessageHandler { message, reply in
        let args = message as! [Any?]
        let propertiesArg = args[0] as! [String: String]
        api.setChatProperties(properties: propertiesArg) { result in
          switch result {
          case .success:
            reply(wrapResult(nil))
          case .failure(let error):
            reply(wrapError(error))
          }
        }
      }
    } else {
      setChatPropertiesChannel.setMessageHandler(nil)
    }
    /// Registers the device push token (FCM on Android, APNs on iOS) so HubSpot
    /// can deliver chat push notifications.
    let setPushTokenChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.hubspot_flutter_chat.HubspotChatHostApi.setPushToken\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      setPushTokenChannel.setMessageHandler { message, reply in
        let args = message as! [Any?]
        let tokenArg = args[0] as! String
        api.setPushToken(token: tokenArg) { result in
          switch result {
          case .success:
            reply(wrapResult(nil))
          case .failure(let error):
            reply(wrapError(error))
          }
        }
      }
    } else {
      setPushTokenChannel.setMessageHandler(nil)
    }
    /// Asks the native SDK whether it recognises and will handle a push payload.
    /// Returns true if the payload was a HubSpot chat notification.
    let handlePushNotificationChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.hubspot_flutter_chat.HubspotChatHostApi.handlePushNotification\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      handlePushNotificationChannel.setMessageHandler { message, reply in
        let args = message as! [Any?]
        let dataArg = args[0] as! [String: String]
        api.handlePushNotification(data: dataArg) { result in
          switch result {
          case .success(let res):
            reply(wrapResult(res))
          case .failure(let error):
            reply(wrapError(error))
          }
        }
      }
    } else {
      handlePushNotificationChannel.setMessageHandler(nil)
    }
    /// Clears the identified visitor and cached conversation state.
    let logoutChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.hubspot_flutter_chat.HubspotChatHostApi.logout\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      logoutChannel.setMessageHandler { _, reply in
        api.logout { result in
          switch result {
          case .success:
            reply(wrapResult(nil))
          case .failure(let error):
            reply(wrapError(error))
          }
        }
      }
    } else {
      logoutChannel.setMessageHandler(nil)
    }
  }
}

/// Native -> Dart callbacks (chat events).
///
/// NOTE: neither native SDK (Android com.hubspot.mobilesdk 1.0.x, iOS
/// HubspotMobileSDK 1.0.x) exposes an unread-message-count observer, so no
/// `onUnreadCountChanged` event is declared — it would be dead on both
/// platforms. Add it back only once the SDKs expose such an observer.
///
/// Generated protocol from Pigeon that represents Flutter messages that can be called from Swift.
protocol HubspotChatFlutterApiProtocol {
  /// A new inbound chat message arrived. Fired on both platforms when a HubSpot
  /// chat push is handed to `handlePushNotification` (Android gates on
  /// `HubspotManager.isHubspotNotification`).
  func onNewMessage(completion: @escaping (Result<Void, PigeonError>) -> Void)
  /// The chat UI was presented.
  func onChatOpened(completion: @escaping (Result<Void, PigeonError>) -> Void)
  /// The chat UI was dismissed. **iOS only** — the Android SDK opens chat as a
  /// separate Activity with no close callback, so Android never fires this.
  func onChatClosed(completion: @escaping (Result<Void, PigeonError>) -> Void)
}
class HubspotChatFlutterApi: HubspotChatFlutterApiProtocol {
  private let binaryMessenger: FlutterBinaryMessenger
  private let messageChannelSuffix: String
  init(binaryMessenger: FlutterBinaryMessenger, messageChannelSuffix: String = "") {
    self.binaryMessenger = binaryMessenger
    self.messageChannelSuffix = messageChannelSuffix.count > 0 ? ".\(messageChannelSuffix)" : ""
  }
  var codec: MessagesPigeonCodec {
    return MessagesPigeonCodec.shared
  }
  /// A new inbound chat message arrived. Fired on both platforms when a HubSpot
  /// chat push is handed to `handlePushNotification` (Android gates on
  /// `HubspotManager.isHubspotNotification`).
  func onNewMessage(completion: @escaping (Result<Void, PigeonError>) -> Void) {
    let channelName: String = "dev.flutter.pigeon.hubspot_flutter_chat.HubspotChatFlutterApi.onNewMessage\(messageChannelSuffix)"
    let channel = FlutterBasicMessageChannel(name: channelName, binaryMessenger: binaryMessenger, codec: codec)
    channel.sendMessage(nil) { response in
      guard let listResponse = response as? [Any?] else {
        completion(.failure(createConnectionError(withChannelName: channelName)))
        return
      }
      if listResponse.count > 1 {
        let code: String = listResponse[0] as! String
        let message: String? = nilOrValue(listResponse[1])
        let details: String? = nilOrValue(listResponse[2])
        completion(.failure(PigeonError(code: code, message: message, details: details)))
      } else {
        completion(.success(()))
      }
    }
  }
  /// The chat UI was presented.
  func onChatOpened(completion: @escaping (Result<Void, PigeonError>) -> Void) {
    let channelName: String = "dev.flutter.pigeon.hubspot_flutter_chat.HubspotChatFlutterApi.onChatOpened\(messageChannelSuffix)"
    let channel = FlutterBasicMessageChannel(name: channelName, binaryMessenger: binaryMessenger, codec: codec)
    channel.sendMessage(nil) { response in
      guard let listResponse = response as? [Any?] else {
        completion(.failure(createConnectionError(withChannelName: channelName)))
        return
      }
      if listResponse.count > 1 {
        let code: String = listResponse[0] as! String
        let message: String? = nilOrValue(listResponse[1])
        let details: String? = nilOrValue(listResponse[2])
        completion(.failure(PigeonError(code: code, message: message, details: details)))
      } else {
        completion(.success(()))
      }
    }
  }
  /// The chat UI was dismissed. **iOS only** — the Android SDK opens chat as a
  /// separate Activity with no close callback, so Android never fires this.
  func onChatClosed(completion: @escaping (Result<Void, PigeonError>) -> Void) {
    let channelName: String = "dev.flutter.pigeon.hubspot_flutter_chat.HubspotChatFlutterApi.onChatClosed\(messageChannelSuffix)"
    let channel = FlutterBasicMessageChannel(name: channelName, binaryMessenger: binaryMessenger, codec: codec)
    channel.sendMessage(nil) { response in
      guard let listResponse = response as? [Any?] else {
        completion(.failure(createConnectionError(withChannelName: channelName)))
        return
      }
      if listResponse.count > 1 {
        let code: String = listResponse[0] as! String
        let message: String? = nilOrValue(listResponse[1])
        let details: String? = nilOrValue(listResponse[2])
        completion(.failure(PigeonError(code: code, message: message, details: details)))
      } else {
        completion(.success(()))
      }
    }
  }
}
